### ISSUE TITLE
希望增加富文本编辑器控件

### ISSUE THREAD

**Issue by bigccc** [WalkingTec/WalkingTec.Mvvm#2]
LayUI已推出简单的富文本编辑器，通常后台管理系统中也会用得到，希望能够增加。
>https://www.layui.com/doc/modules/layedit.html

**Comment by liuliang-wt** [comment]
下个小版本加入

**Comment by alienwow** [comment]
> LayUI已推出简单的富文本编辑器，通常后台管理系统中也会用得到，希望能够增加。
> 
> > https://www.layui.com/doc/modules/layedit.html

已经在v2.2.0版本中发布

**Comment by liuliang-wt** [comment]
目前框架还支持UEditor
