### ISSUE TITLE
为了支持网站前台页面的2个需求建议:

### ISSUE THREAD

**Issue by bigccc** [WalkingTec/WalkingTec.Mvvm#3]
因为实际项目需求中，除了网站后台还需要前台页面配合使用，为了支持这一功能有2个建议：
- 支持跨域请求，例如www.xxx.com是前台页面，admin.xxx.com是后台页面。
- 可以自定义路由，例如xxx.com是前台页面，xxx.com/admin是后台页面。

**Comment by alienwow** [comment]
> 因为实际项目需求中，除了网站后台还需要前台页面配合使用，为了支持这一功能有2个建议：
> 
> * 支持跨域请求，例如www.xxx.com是前台页面，admin.xxx.com是后台页面。
> * 可以自定义路由，例如xxx.com是前台页面，xxx.com/admin是后台页面。

嗯 这个我们会考虑在之后的版本中添加的。
感谢您的宝贵建议！

**Comment by liuliang-wt** [comment]
已在2.2.0版本重增加

**Comment by tiger2014** [comment]
现在最新的版本是 ：v1.3.37。不知道2.2.0版本在哪里？

**Comment by liuliang-wt** [comment]
因为后期都是nuget包了，我们也提供了线上一键创建项目的功能，就没有在GitHub上发布Release了。你直接在nuget上引用就可以了。具体请参见我们的文档 http://wtmdoc.walkingtec.cn
