### ISSUE TITLE
var data = DC.Set<FrameworkMenu>().ToList();  这句话在mysql下 一直报错 http 400

### ISSUE THREAD

**Issue by ganmk** [WalkingTec/WalkingTec.Mvvm#4]
还有  添加的了用户之后 mysql环境下 日期格式提示错误；

**Comment by ganmk** [comment]
src\WalkingTec.Mvvm.Mvc.Admin\Areas\_Admin\ViewModels\FrameworkMenuVMs\FrameworkMenuListVM.cs
115行；

**Comment by liuliang-wt** [comment]
可以把具体的错误贴出来么

**Comment by ganmk** [comment]
![image](https://user-images.githubusercontent.com/6767533/52922901-8b179900-335f-11e9-9efd-8f8e7127135b.png)

**Comment by ganmk** [comment]
就是在管理菜单的时候 报400

**Comment by ganmk** [comment]
![image](https://user-images.githubusercontent.com/6767533/52922968-eea1c680-335f-11e9-8577-aa181086993c.png)

**Comment by ganmk** [comment]
![image](https://user-images.githubusercontent.com/6767533/52924180-830f2780-3366-11e9-9d8c-46da0a06046b.png)

**Comment by ganmk** [comment]
[190218102634.zip](https://github.com/WalkingTec/WalkingTec.Mvvm/files/2873996/190218102634.zip)

**Comment by liuliang-wt** [comment]
经过沟通，是这位同学mysql连接字符串写的不对。。。
