### ISSUE TITLE
新增加的实体 手动迁移 也不成功

### ISSUE THREAD

**Issue by ganmk** [WalkingTec/WalkingTec.Mvvm#5]
code first  新增加的实体 手动迁移 也不成功 是什么原因呢？

**Comment by ganmk** [comment]
@liuliang-wt

**Comment by liuliang-wt** [comment]
EF中目前不可以自动更新数据库，最简单的办法是删了已有的库，让EF重新生成新库，或者手动在数据库中添加和实体对应的表
